### PR TITLE
Update libraries

### PR DESCRIPTION
**Pull request by ademar111190**
Update retrofit to 2.1, okhttp mockwebserver to 3.3.1 and assertj to 3.4.1

### CODE REVIEW

**Comment by ademar111190** [comment]
I tested the project with `$ ./gradlew test` and it seems that the project is stable. If there is others tests to do please let me know.

**Comment by aurae** [comment]
Awesome, thanks for the contribution! I'll merge this as soon as I'm back on my machine.

**Comment by aurae** [comment]
I will release this as 1.4.1 shortly. Thank you again for the contribution!

**Comment by ademar111190** [comment]
Thank you! =D

**Review by PrinceSagor — CHANGES_REQUESTED** [review]
My...boss...best...pewor...allah...💯❤️‍🔥

**Pull request merged**
